# This is a basic workflow to help you get started with Actions

name: Docker Series Builds

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      # Runs a single command using the runners shell
      - name: docker build
        run: |
          docker build ./c# -t chuimistro/csharp:1.0.0
          
      - name: docker build nodejs
        run: |
          docker build ./nodejs -t chuimistro/nodejs:1.0.0
        
      - name: docker build python
        run: |
          docker build ./python -t chuimistro/python:1.0.0
      - name: docker build golang
        run: |
          docker build ./golang -t chuimistro/golang:1.0.0
      - name: docker push
        run: |
          docker push chuimistro/csharp:1.0.0
          docker push chuimistro/nodejs:1.0.0
          docker push chuimistro/python:1.0.0
          docker push chuimistro/golang:1.0.0
